"use client";

import { useState, useEffect, useCallback, Suspense } from "react";
import { useSession } from "next-auth/react";
import { useParams, useSearchParams } from "next/navigation";
import Link from "next/link";
import { Card, CardHeader, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

interface Service {
  id: string;
  name: string;
  price: string;
  category: string | null;
  is_active: boolean;
}

interface Patient {
  id: string;
  patient_number: string;
  full_name: string;
  phone: string | null;
}

interface Appointment {
  id: string;
  appointment_date: string;
  time_slot_start: string;
  token_number: number;
  status: string;
  doctor: {
    id: string;
    full_name: string;
  };
}

interface InvoiceItem {
  service_id: string;
  name: string;
  quantity: number;
  unit_price: number;
  amount: number;
}

interface Invoice {
  id: string;
  invoice_number: string;
  items: InvoiceItem[];
  subtotal: string;
  discount: string;
  tax: string;
  total: string;
  payment_mode: string;
  payment_status: string;
  notes: string | null;
  created_at: string;
  patient: Patient;
  appointment?: {
    id: string;
    appointment_date: string;
    doctor: {
      id: string;
      full_name: string;
    };
  };
}

interface Clinic {
  id: string;
  name: string;
  address: string | null;
  phone: string | null;
  email: string | null;
  logo_url: string | null;
}

// Translations
const translations = {
  en: {
    title: "Billing",
    subtitle: "Create invoices and manage billing",
    createInvoice: "Create Invoice",
    recentInvoices: "Recent Invoices",
    selectPatient: "Select Patient",
    searchPatient: "Search patient by phone or name",
    searching: "Searching...",
    noPatients: "No patients found",
    patientInfo: "Patient Information",
    appointmentInfo: "Appointment",
    noAppointment: "No linked appointment",
    selectAppointment: "Link to Appointment (Optional)",
    services: "Services",
    addService: "Add Service",
    manageServices: "Manage Services",
    noServices: "No services available",
    noServicesMessage: "Add services to your catalog first.",
    service: "Service",
    quantity: "Qty",
    unitPrice: "Unit Price",
    amount: "Amount",
    actions: "Actions",
    remove: "Remove",
    subtotal: "Subtotal",
    discount: "Discount",
    tax: "Tax (VAT 13%)",
    total: "Total",
    paymentMode: "Payment Mode",
    cash: "Cash",
    card: "Card",
    upi: "UPI",
    bankTransfer: "Bank Transfer",
    insurance: "Insurance",
    credit: "Credit (Khata)",
    paymentStatus: "Payment Status",
    pending: "Pending",
    paid: "Paid",
    partial: "Partial",
    notes: "Notes",
    notesPlaceholder: "Optional notes...",
    generateInvoice: "Generate Invoice",
    generating: "Generating...",
    invoiceGenerated: "Invoice generated successfully",
    printReceipt: "Print Receipt",
    viewInvoice: "View Invoice",
    invoiceNumber: "Invoice #",
    date: "Date",
    time: "Time",
    patient: "Patient",
    doctor: "Doctor",
    status: "Status",
    totalAmount: "Amount",
    noInvoices: "No invoices yet",
    noInvoicesMessage: "Create your first invoice to get started.",
    loginRequired: "Please log in to access billing",
    login: "Login",
    loading: "Loading...",
    errorLoading: "Failed to load data",
    retry: "Retry",
    noClinic: "No Verified Clinic",
    noClinicMessage: "You don't have a verified clinic yet.",
    back: "Back to Dashboard",
    error: "An error occurred",
    required: "Required",
    addAtLeastOneItem: "Add at least one item",
    clearPatient: "Change Patient",
    receipt: "Receipt",
    thankYou: "Thank you for your visit!",
    generatedBy: "Generated by",
  },
  ne: {
    title: "बिलिङ",
    subtitle: "इनभ्वाइसहरू बनाउनुहोस् र बिलिङ व्यवस्थापन गर्नुहोस्",
    createInvoice: "इनभ्वाइस बनाउनुहोस्",
    recentInvoices: "हालका इनभ्वाइसहरू",
    selectPatient: "बिरामी छान्नुहोस्",
    searchPatient: "फोन वा नामले बिरामी खोज्नुहोस्",
    searching: "खोज्दै...",
    noPatients: "कुनै बिरामी भेटिएन",
    patientInfo: "बिरामी जानकारी",
    appointmentInfo: "अपोइन्टमेन्ट",
    noAppointment: "कुनै लिंक गरिएको अपोइन्टमेन्ट छैन",
    selectAppointment: "अपोइन्टमेन्टमा लिंक गर्नुहोस् (वैकल्पिक)",
    services: "सेवाहरू",
    addService: "सेवा थप्नुहोस्",
    manageServices: "सेवाहरू व्यवस्थापन गर्नुहोस्",
    noServices: "सेवाहरू उपलब्ध छैनन्",
    noServicesMessage: "पहिले आफ्नो क्याटलगमा सेवाहरू थप्नुहोस्।",
    service: "सेवा",
    quantity: "मात्रा",
    unitPrice: "एकाइ मूल्य",
    amount: "रकम",
    actions: "कार्यहरू",
    remove: "हटाउनुहोस्",
    subtotal: "उप-जम्मा",
    discount: "छुट",
    tax: "कर (भ्याट १३%)",
    total: "जम्मा",
    paymentMode: "भुक्तानी मोड",
    cash: "नगद",
    card: "कार्ड",
    upi: "यूपीआई",
    bankTransfer: "बैंक ट्रान्सफर",
    insurance: "बीमा",
    credit: "उधारो (खाता)",
    paymentStatus: "भुक्तानी स्थिति",
    pending: "बाँकी",
    paid: "भुक्तान भयो",
    partial: "आंशिक",
    notes: "टिप्पणीहरू",
    notesPlaceholder: "वैकल्पिक टिप्पणीहरू...",
    generateInvoice: "इनभ्वाइस बनाउनुहोस्",
    generating: "बनाउँदै...",
    invoiceGenerated: "इनभ्वाइस सफलतापूर्वक बनाइयो",
    printReceipt: "रसिद छाप्नुहोस्",
    viewInvoice: "इनभ्वाइस हेर्नुहोस्",
    invoiceNumber: "इनभ्वाइस #",
    date: "मिति",
    time: "समय",
    patient: "बिरामी",
    doctor: "डाक्टर",
    status: "स्थिति",
    totalAmount: "रकम",
    noInvoices: "अझै इनभ्वाइसहरू छैनन्",
    noInvoicesMessage: "सुरु गर्न आफ्नो पहिलो इनभ्वाइस बनाउनुहोस्।",
    loginRequired: "बिलिङ पहुँच गर्न कृपया लगइन गर्नुहोस्",
    login: "लगइन गर्नुहोस्",
    loading: "लोड हुँदैछ...",
    errorLoading: "डेटा लोड गर्न असफल भयो",
    retry: "पुन: प्रयास गर्नुहोस्",
    noClinic: "कुनै प्रमाणित क्लिनिक छैन",
    noClinicMessage: "तपाईंसँग अझै प्रमाणित क्लिनिक छैन।",
    back: "ड्यासबोर्डमा फर्कनुहोस्",
    error: "त्रुटि भयो",
    required: "आवश्यक",
    addAtLeastOneItem: "कम्तिमा एउटा वस्तु थप्नुहोस्",
    clearPatient: "बिरामी परिवर्तन गर्नुहोस्",
    receipt: "रसिद",
    thankYou: "तपाईंको भ्रमणको लागि धन्यवाद!",
    generatedBy: "द्वारा उत्पन्न",
  },
};

const PAYMENT_MODES = [
  { value: "CASH", label: { en: "Cash", ne: "नगद" } },
  { value: "CARD", label: { en: "Card", ne: "कार्ड" } },
  { value: "UPI", label: { en: "UPI", ne: "यूपीआई" } },
  { value: "BANK_TRANSFER", label: { en: "Bank Transfer", ne: "बैंक ट्रान्सफर" } },
  { value: "INSURANCE", label: { en: "Insurance", ne: "बीमा" } },
  { value: "CREDIT", label: { en: "Credit (Khata)", ne: "उधारो (खाता)" } },
];

const PAYMENT_STATUSES = [
  { value: "PENDING", label: { en: "Pending", ne: "बाँकी" }, color: "bg-primary-yellow text-foreground" },
  { value: "PAID", label: { en: "Paid", ne: "भुक्तान भयो" }, color: "bg-verified text-white" },
  { value: "PARTIAL", label: { en: "Partial", ne: "आंशिक" }, color: "bg-primary-blue text-white" },
];

const TAX_RATE = 0.13; // 13% VAT

function BillingPageContent() {
  const { data: session, status } = useSession();
  const params = useParams<{ lang: string }>();
  const searchParams = useSearchParams();
  const lang = params?.lang || "en";
  const t = translations[lang as keyof typeof translations] || translations.en;

  // Pre-selected patient from URL
  const preselectedPatientId = searchParams.get("patientId");

  // Data state
  const [services, setServices] = useState<Service[]>([]);
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [clinic, setClinic] = useState<Clinic | null>(null);

  // UI state
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [noClinic, setNoClinic] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);

  // Patient search state
  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState<Patient[]>([]);
  const [searching, setSearching] = useState(false);
  const [selectedPatient, setSelectedPatient] = useState<Patient | null>(null);

  // Patient appointments state
  const [patientAppointments, setPatientAppointments] = useState<Appointment[]>([]);
  const [selectedAppointment, setSelectedAppointment] = useState<string>("");

  // Invoice items state
  const [invoiceItems, setInvoiceItems] = useState<InvoiceItem[]>([]);
  const [selectedServiceId, setSelectedServiceId] = useState("");

  // Invoice form state
  const [discount, setDiscount] = useState("0");
  const [includeTax, setIncludeTax] = useState(false);
  const [paymentMode, setPaymentMode] = useState("CASH");
  const [paymentStatus, setPaymentStatus] = useState("PAID");
  const [notes, setNotes] = useState("");
  const [generating, setGenerating] = useState(false);

  // Print state
  const [printInvoice, setPrintInvoice] = useState<Invoice | null>(null);

  // Calculated values
  const subtotal = invoiceItems.reduce((sum, item) => sum + item.amount, 0);
  const discountAmount = Number(discount) || 0;
  const taxAmount = includeTax ? (subtotal - discountAmount) * TAX_RATE : 0;
  const total = subtotal - discountAmount + taxAmount;

  const fetchData = useCallback(async () => {
    setLoading(true);
    setError(null);
    setNoClinic(false);

    try {
      // Fetch services
      const servicesResponse = await fetch("/api/clinic/services");
      if (servicesResponse.status === 404) {
        const data = await servicesResponse.json();
        if (data.code === "NO_CLINIC") {
          setNoClinic(true);
          return;
        }
      }

      if (servicesResponse.ok) {
        const data = await servicesResponse.json();
        setServices(data.services?.filter((s: Service) => s.is_active) || []);
      }

      // Fetch recent invoices
      const invoicesResponse = await fetch("/api/clinic/invoices?limit=10");
      if (invoicesResponse.ok) {
        const data = await invoicesResponse.json();
        setInvoices(data.invoices || []);
      }

      // Get clinic info
      const dashboardResponse = await fetch("/api/clinic/dashboard");
      if (dashboardResponse.ok) {
        const data = await dashboardResponse.json();
        setClinic(data.clinic);
      }
    } catch (err) {
      console.error("Error fetching data:", err);
      setError(t.errorLoading);
    } finally {
      setLoading(false);
    }
  }, [t.errorLoading]);

  useEffect(() => {
    if (status === "authenticated") {
      fetchData();
    } else if (status === "unauthenticated") {
      setLoading(false);
    }
  }, [status, fetchData]);

  // Search patients
  const handleSearch = async () => {
    if (!searchQuery.trim() || searchQuery.length < 2) {
      setSearchResults([]);
      return;
    }

    setSearching(true);
    try {
      const response = await fetch(`/api/clinic/patients/search?q=${encodeURIComponent(searchQuery)}`);
      if (response.ok) {
        const data = await response.json();
        setSearchResults(data.patients || []);
      }
    } catch (err) {
      console.error("Error searching patients:", err);
    } finally {
      setSearching(false);
    }
  };

  useEffect(() => {
    const timer = setTimeout(() => {
      handleSearch();
    }, 300);
    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchQuery]);

  // Fetch patient appointments when patient is selected
  const fetchPatientAppointments = async (patientId: string) => {
    try {
      const response = await fetch(`/api/clinic/queue?patientId=${patientId}&includeAllDates=true`);
      if (response.ok) {
        const data = await response.json();
        // Filter to recent appointments without invoices
        setPatientAppointments(data.appointments || []);
      }
    } catch (err) {
      console.error("Error fetching patient appointments:", err);
    }
  };

  // Handle patient selection
  const handleSelectPatient = async (patient: Patient) => {
    setSelectedPatient(patient);
    setSearchResults([]);
    setSearchQuery("");
    await fetchPatientAppointments(patient.id);
  };

  // Handle preselected patient
  useEffect(() => {
    if (preselectedPatientId && !selectedPatient && !loading) {
      // Fetch patient by ID
      const fetchPatient = async () => {
        try {
          const response = await fetch(`/api/clinic/patients/search?id=${preselectedPatientId}`);
          if (response.ok) {
            const data = await response.json();
            if (data.patients?.length > 0) {
              handleSelectPatient(data.patients[0]);
            }
          }
        } catch (err) {
          console.error("Error fetching preselected patient:", err);
        }
      };
      fetchPatient();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [preselectedPatientId, loading]);

  // Clear patient selection
  const handleClearPatient = () => {
    setSelectedPatient(null);
    setPatientAppointments([]);
    setSelectedAppointment("");
    setInvoiceItems([]);
  };

  // Add service to invoice
  const handleAddService = () => {
    if (!selectedServiceId) return;

    const service = services.find((s) => s.id === selectedServiceId);
    if (!service) return;

    // Check if already in items
    const existingIndex = invoiceItems.findIndex((item) => item.service_id === service.id);
    if (existingIndex >= 0) {
      // Increment quantity
      const newItems = [...invoiceItems];
      newItems[existingIndex].quantity += 1;
      newItems[existingIndex].amount = newItems[existingIndex].quantity * newItems[existingIndex].unit_price;
      setInvoiceItems(newItems);
    } else {
      // Add new item
      const unitPrice = Number(service.price);
      setInvoiceItems([
        ...invoiceItems,
        {
          service_id: service.id,
          name: service.name,
          quantity: 1,
          unit_price: unitPrice,
          amount: unitPrice,
        },
      ]);
    }

    setSelectedServiceId("");
  };

  // Update item quantity
  const handleUpdateQuantity = (index: number, quantity: number) => {
    if (quantity < 1) return;
    const newItems = [...invoiceItems];
    newItems[index].quantity = quantity;
    newItems[index].amount = quantity * newItems[index].unit_price;
    setInvoiceItems(newItems);
  };

  // Remove item
  const handleRemoveItem = (index: number) => {
    setInvoiceItems(invoiceItems.filter((_, i) => i !== index));
  };

  // Generate invoice
  const handleGenerateInvoice = async () => {
    if (!selectedPatient) {
      setMessage({ type: "error", text: t.required });
      return;
    }

    if (invoiceItems.length === 0) {
      setMessage({ type: "error", text: t.addAtLeastOneItem });
      return;
    }

    setGenerating(true);
    setMessage(null);

    try {
      const response = await fetch("/api/clinic/invoices", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          patient_id: selectedPatient.id,
          appointment_id: selectedAppointment || null,
          items: invoiceItems,
          discount: discountAmount,
          tax: taxAmount,
          payment_mode: paymentMode,
          payment_status: paymentStatus,
          notes: notes.trim() || null,
        }),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Failed to generate invoice");
      }

      const data = await response.json();
      setMessage({ type: "success", text: `${t.invoiceGenerated} - ${data.invoice.invoice_number}` });

      // Show print dialog
      setPrintInvoice(data.invoice);

      // Reset form
      setInvoiceItems([]);
      setDiscount("0");
      setIncludeTax(false);
      setNotes("");
      setSelectedAppointment("");

      // Refresh invoices
      fetchData();
    } catch (err) {
      console.error("Error generating invoice:", err);
      setMessage({ type: "error", text: err instanceof Error ? err.message : t.error });
    } finally {
      setGenerating(false);
    }
  };

  // Handle print
  const handlePrint = () => {
    window.print();
  };

  // Format currency
  const formatCurrency = (amount: number | string) => {
    return `NPR ${Number(amount).toLocaleString("en-NP", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  };

  // Loading state
  if (status === "loading" || loading) {
    return (
      <main className="min-h-screen bg-background py-8 px-4 sm:px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <Card decorator="blue" decoratorPosition="top-right">
            <CardContent className="py-12 text-center">
              <div className="animate-pulse">
                <div className="w-12 h-12 bg-primary-blue/20 rounded-full mx-auto mb-4" />
                <div className="h-4 bg-foreground/10 rounded w-48 mx-auto" />
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    );
  }

  // Not authenticated
  if (!session) {
    return (
      <main className="min-h-screen bg-background py-8 px-4 sm:px-6 lg:px-8">
        <div className="max-w-2xl mx-auto">
          <Card decorator="red" decoratorPosition="top-right">
            <CardHeader>
              <h1 className="text-3xl font-bold text-foreground">{t.title}</h1>
            </CardHeader>
            <CardContent>
              <p className="text-foreground/70 mb-6">{t.loginRequired}</p>
              <Link href={`/${lang}/login?callbackUrl=/${lang}/clinic/dashboard/billing`}>
                <Button variant="primary">{t.login}</Button>
              </Link>
            </CardContent>
          </Card>
        </div>
      </main>
    );
  }

  // No clinic found
  if (noClinic) {
    return (
      <main className="min-h-screen bg-background py-8 px-4 sm:px-6 lg:px-8">
        <div className="max-w-2xl mx-auto">
          <Card decorator="yellow" decoratorPosition="top-right">
            <CardHeader>
              <h1 className="text-3xl font-bold text-foreground">{t.noClinic}</h1>
            </CardHeader>
            <CardContent>
              <p className="text-foreground/70 mb-6">{t.noClinicMessage}</p>
              <Link href={`/${lang}/clinic/dashboard`}>
                <Button variant="primary">{t.back}</Button>
              </Link>
            </CardContent>
          </Card>
        </div>
      </main>
    );
  }

  // Error state
  if (error) {
    return (
      <main className="min-h-screen bg-background py-8 px-4 sm:px-6 lg:px-8">
        <div className="max-w-2xl mx-auto">
          <Card decorator="red" decoratorPosition="top-right">
            <CardHeader>
              <h1 className="text-3xl font-bold text-foreground">{t.title}</h1>
            </CardHeader>
            <CardContent>
              <p className="text-foreground/70 mb-6">{error}</p>
              <Button variant="primary" onClick={fetchData}>
                {t.retry}
              </Button>
            </CardContent>
          </Card>
        </div>
      </main>
    );
  }

  // Print receipt view
  if (printInvoice) {
    return (
      <>
        {/* Print view */}
        <div className="print:block hidden p-8">
          <div className="max-w-md mx-auto border-2 border-foreground p-6">
            {/* Header */}
            <div className="text-center border-b-2 border-dashed border-foreground pb-4 mb-4">
              <h1 className="text-2xl font-bold">{clinic?.name}</h1>
              {clinic?.address && <p className="text-sm">{clinic.address}</p>}
              {clinic?.phone && <p className="text-sm">Tel: {clinic.phone}</p>}
              <p className="text-lg font-black mt-2">{t.receipt}</p>
            </div>

            {/* Invoice Info */}
            <div className="border-b border-dashed border-foreground/50 pb-4 mb-4 text-sm">
              <div className="flex justify-between">
                <span>{t.invoiceNumber}:</span>
                <span className="font-bold">{printInvoice.invoice_number}</span>
              </div>
              <div className="flex justify-between">
                <span>{t.date}:</span>
                <span>{new Date(printInvoice.created_at).toLocaleDateString()}</span>
              </div>
              <div className="flex justify-between">
                <span>{t.patient}:</span>
                <span>{printInvoice.patient.full_name}</span>
              </div>
              {printInvoice.appointment?.doctor && (
                <div className="flex justify-between">
                  <span>{t.doctor}:</span>
                  <span>{printInvoice.appointment.doctor.full_name.startsWith("Dr.") ? "" : "Dr. "}{printInvoice.appointment.doctor.full_name}</span>
                </div>
              )}
            </div>

            {/* Items */}
            <table className="w-full text-sm mb-4">
              <thead>
                <tr className="border-b border-foreground">
                  <th className="text-left py-1">{t.service}</th>
                  <th className="text-center py-1">{t.quantity}</th>
                  <th className="text-right py-1">{t.amount}</th>
                </tr>
              </thead>
              <tbody>
                {(printInvoice.items as InvoiceItem[]).map((item, index) => (
                  <tr key={index} className="border-b border-dashed border-foreground/30">
                    <td className="py-1">{item.name}</td>
                    <td className="text-center py-1">{item.quantity}</td>
                    <td className="text-right py-1">{formatCurrency(item.amount)}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            {/* Totals */}
            <div className="border-t-2 border-foreground pt-2 text-sm">
              <div className="flex justify-between">
                <span>{t.subtotal}:</span>
                <span>{formatCurrency(printInvoice.subtotal)}</span>
              </div>
              {Number(printInvoice.discount) > 0 && (
                <div className="flex justify-between text-primary-red">
                  <span>{t.discount}:</span>
                  <span>-{formatCurrency(printInvoice.discount)}</span>
                </div>
              )}
              {Number(printInvoice.tax) > 0 && (
                <div className="flex justify-between">
                  <span>{t.tax}:</span>
                  <span>{formatCurrency(printInvoice.tax)}</span>
                </div>
              )}
              <div className="flex justify-between font-black text-lg mt-2 pt-2 border-t border-foreground">
                <span>{t.total}:</span>
                <span>{formatCurrency(printInvoice.total)}</span>
              </div>
            </div>

            {/* Payment Info */}
            <div className="mt-4 pt-4 border-t border-dashed border-foreground/50 text-sm">
              <div className="flex justify-between">
                <span>{t.paymentMode}:</span>
                <span>{PAYMENT_MODES.find((m) => m.value === printInvoice.payment_mode)?.label[lang as keyof typeof PAYMENT_MODES[0]["label"]] || printInvoice.payment_mode}</span>
              </div>
              <div className="flex justify-between">
                <span>{t.status}:</span>
                <span className="font-bold">{PAYMENT_STATUSES.find((s) => s.value === printInvoice.payment_status)?.label[lang as keyof typeof PAYMENT_STATUSES[0]["label"]] || printInvoice.payment_status}</span>
              </div>
            </div>

            {/* Footer */}
            <div className="mt-6 pt-4 border-t-2 border-dashed border-foreground text-center text-sm">
              <p className="font-bold">{t.thankYou}</p>
              <p className="text-xs text-foreground/60 mt-2">{t.generatedBy} DoctorSewa</p>
            </div>
          </div>
        </div>

        {/* Screen view - close print dialog */}
        <main className="min-h-screen bg-background py-8 px-4 sm:px-6 lg:px-8 print:hidden">
          <div className="max-w-lg mx-auto">
            <Card decorator="blue" decoratorPosition="top-left">
              <CardHeader>
                <h2 className="text-xl font-bold text-center">{t.invoiceGenerated}</h2>
              </CardHeader>
              <CardContent className="text-center">
                <div className="w-20 h-20 bg-verified rounded-full mx-auto mb-4 flex items-center justify-center">
                  <svg className="w-10 h-10 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                  </svg>
                </div>
                <p className="text-2xl font-black mb-6">{printInvoice.invoice_number}</p>
                <div className="flex gap-4">
                  <Button variant="primary" onClick={handlePrint} className="flex-1">
                    {t.printReceipt}
                  </Button>
                  <Button variant="outline" onClick={() => setPrintInvoice(null)} className="flex-1">
                    {t.back}
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </main>
      </>
    );
  }

  return (
    <main className="min-h-screen bg-background py-8 px-4 sm:px-6 lg:px-8 print:hidden">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-8">
          <div>
            <Link
              href={`/${lang}/clinic/dashboard`}
              className="inline-flex items-center text-foreground/70 hover:text-foreground mb-2 transition-colors"
            >
              <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
              </svg>
              {t.back}
            </Link>
            <h1 className="text-3xl lg:text-4xl font-bold text-foreground">{t.title}</h1>
            <p className="text-foreground/60">{t.subtitle}</p>
          </div>
          <div className="mt-4 sm:mt-0">
            <Link href={`/${lang}/clinic/dashboard/services`}>
              <Button variant="outline">{t.manageServices}</Button>
            </Link>
          </div>
        </div>

        {/* Message */}
        {message && (
          <div
            className={`mb-6 p-4 border-2 ${
              message.type === "success"
                ? "bg-verified/10 border-verified text-verified"
                : "bg-primary-red/10 border-primary-red text-primary-red"
            }`}
          >
            {message.text}
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Create Invoice Form */}
          <div className="lg:col-span-2 space-y-6">
            {/* Patient Selection */}
            <Card decorator="blue" decoratorPosition="top-left">
              <CardHeader>
                <h2 className="text-lg font-bold uppercase tracking-wider">{t.selectPatient}</h2>
              </CardHeader>
              <CardContent>
                {!selectedPatient ? (
                  <div>
                    <input
                      type="text"
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                      placeholder={t.searchPatient}
                      className="w-full p-3 border-4 border-foreground bg-white text-foreground font-medium focus:outline-none focus:border-primary-blue transition-colors"
                    />
                    {searching && <p className="mt-2 text-sm text-foreground/60">{t.searching}</p>}
                    {searchResults.length > 0 && (
                      <div className="mt-2 border-2 border-foreground bg-white max-h-48 overflow-y-auto">
                        {searchResults.map((patient) => (
                          <button
                            key={patient.id}
                            type="button"
                            onClick={() => handleSelectPatient(patient)}
                            className="w-full p-3 text-left hover:bg-foreground/5 border-b border-foreground/10 last:border-b-0"
                          >
                            <p className="font-bold">{patient.full_name}</p>
                            <p className="text-sm text-foreground/60">
                              {patient.phone} • {patient.patient_number}
                            </p>
                          </button>
                        ))}
                      </div>
                    )}
                    {searchQuery.length >= 2 && !searching && searchResults.length === 0 && (
                      <p className="mt-2 text-sm text-foreground/60">{t.noPatients}</p>
                    )}
                  </div>
                ) : (
                  <div className="p-4 bg-verified/10 border-2 border-verified">
                    <div className="flex items-start justify-between">
                      <div>
                        <p className="text-xs font-bold uppercase tracking-wider text-verified mb-1">
                          {t.patientInfo}
                        </p>
                        <p className="font-bold text-lg">{selectedPatient.full_name}</p>
                        <p className="text-sm text-foreground/60">
                          {selectedPatient.patient_number} • {selectedPatient.phone}
                        </p>
                      </div>
                      <Button variant="ghost" size="sm" onClick={handleClearPatient}>
                        {t.clearPatient}
                      </Button>
                    </div>

                    {/* Appointment Selection */}
                    {patientAppointments.length > 0 && (
                      <div className="mt-4 pt-4 border-t border-verified/30">
                        <label className="block text-sm font-bold uppercase tracking-wider text-foreground/60 mb-2">
                          {t.selectAppointment}
                        </label>
                        <select
                          value={selectedAppointment}
                          onChange={(e) => setSelectedAppointment(e.target.value)}
                          className="w-full p-2 border-2 border-foreground bg-white text-foreground font-medium focus:outline-none focus:border-primary-blue"
                        >
                          <option value="">{t.noAppointment}</option>
                          {patientAppointments.map((apt) => (
                            <option key={apt.id} value={apt.id}>
                              {new Date(apt.appointment_date).toLocaleDateString()} - {apt.time_slot_start} - {apt.doctor.full_name.startsWith("Dr.") ? "" : "Dr. "}{apt.doctor.full_name} (Token #{apt.token_number})
                            </option>
                          ))}
                        </select>
                      </div>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Services Selection */}
            <Card decorator="red" decoratorPosition="top-right">
              <CardHeader>
                <h2 className="text-lg font-bold uppercase tracking-wider">{t.services}</h2>
              </CardHeader>
              <CardContent>
                {services.length === 0 ? (
                  <div className="text-center py-8">
                    <p className="text-foreground/60 mb-4">{t.noServicesMessage}</p>
                    <Link href={`/${lang}/clinic/dashboard/services`}>
                      <Button variant="primary">{t.manageServices}</Button>
                    </Link>
                  </div>
                ) : (
                  <>
                    {/* Add Service */}
                    <div className="flex gap-2 mb-4">
                      <select
                        value={selectedServiceId}
                        onChange={(e) => setSelectedServiceId(e.target.value)}
                        className="flex-1 p-3 border-4 border-foreground bg-white text-foreground font-medium focus:outline-none focus:border-primary-blue"
                      >
                        <option value="">{t.addService}...</option>
                        {services.map((service) => (
                          <option key={service.id} value={service.id}>
                            {service.name} - {formatCurrency(service.price)}
                          </option>
                        ))}
                      </select>
                      <Button variant="primary" onClick={handleAddService} disabled={!selectedServiceId}>
                        +
                      </Button>
                    </div>

                    {/* Invoice Items Table */}
                    {invoiceItems.length > 0 && (
                      <div className="overflow-x-auto">
                        <table className="w-full">
                          <thead>
                            <tr className="border-b-2 border-foreground">
                              <th className="text-left py-2 text-sm font-bold uppercase tracking-wider">{t.service}</th>
                              <th className="text-center py-2 text-sm font-bold uppercase tracking-wider w-24">{t.quantity}</th>
                              <th className="text-right py-2 text-sm font-bold uppercase tracking-wider">{t.unitPrice}</th>
                              <th className="text-right py-2 text-sm font-bold uppercase tracking-wider">{t.amount}</th>
                              <th className="text-center py-2 text-sm font-bold uppercase tracking-wider w-20">{t.actions}</th>
                            </tr>
                          </thead>
                          <tbody>
                            {invoiceItems.map((item, index) => (
                              <tr key={index} className="border-b border-foreground/20">
                                <td className="py-3">{item.name}</td>
                                <td className="py-3">
                                  <input
                                    type="number"
                                    value={item.quantity}
                                    onChange={(e) => handleUpdateQuantity(index, parseInt(e.target.value) || 1)}
                                    min="1"
                                    className="w-16 p-1 text-center border-2 border-foreground bg-white"
                                  />
                                </td>
                                <td className="py-3 text-right">{formatCurrency(item.unit_price)}</td>
                                <td className="py-3 text-right font-bold">{formatCurrency(item.amount)}</td>
                                <td className="py-3 text-center">
                                  <button
                                    onClick={() => handleRemoveItem(index)}
                                    className="text-primary-red hover:text-primary-red/80"
                                  >
                                    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                    </svg>
                                  </button>
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}

                    {/* Totals */}
                    {invoiceItems.length > 0 && (
                      <div className="mt-4 pt-4 border-t-2 border-foreground space-y-2">
                        <div className="flex justify-between">
                          <span className="text-foreground/60">{t.subtotal}:</span>
                          <span className="font-bold">{formatCurrency(subtotal)}</span>
                        </div>

                        {/* Discount */}
                        <div className="flex justify-between items-center">
                          <label className="text-foreground/60">{t.discount}:</label>
                          <div className="flex items-center gap-2">
                            <span>NPR</span>
                            <input
                              type="number"
                              value={discount}
                              onChange={(e) => setDiscount(e.target.value)}
                              min="0"
                              max={subtotal}
                              className="w-24 p-1 text-right border-2 border-foreground bg-white"
                            />
                          </div>
                        </div>

                        {/* Tax Toggle */}
                        <div className="flex justify-between items-center">
                          <label className="flex items-center gap-2">
                            <input
                              type="checkbox"
                              checked={includeTax}
                              onChange={(e) => setIncludeTax(e.target.checked)}
                              className="w-4 h-4"
                            />
                            <span className="text-foreground/60">{t.tax}:</span>
                          </label>
                          <span className={includeTax ? "font-bold" : "text-foreground/40"}>
                            {formatCurrency(taxAmount)}
                          </span>
                        </div>

                        <div className="flex justify-between pt-2 border-t-2 border-foreground">
                          <span className="text-xl font-black">{t.total}:</span>
                          <span className="text-xl font-black text-primary-blue">{formatCurrency(total)}</span>
                        </div>
                      </div>
                    )}
                  </>
                )}
              </CardContent>
            </Card>

            {/* Payment Options */}
            {invoiceItems.length > 0 && (
              <Card decorator="yellow" decoratorPosition="top-left">
                <CardHeader>
                  <h2 className="text-lg font-bold uppercase tracking-wider">{t.paymentMode}</h2>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 mb-4">
                    {PAYMENT_MODES.map((mode) => (
                      <button
                        key={mode.value}
                        onClick={() => setPaymentMode(mode.value)}
                        className={`p-3 border-2 border-foreground font-bold text-sm transition-colors ${
                          paymentMode === mode.value
                            ? "bg-foreground text-white"
                            : "bg-white text-foreground hover:bg-foreground/5"
                        }`}
                      >
                        {mode.label[lang as keyof typeof mode.label] || mode.label.en}
                      </button>
                    ))}
                  </div>

                  <div className="flex gap-2 mb-4">
                    {PAYMENT_STATUSES.map((status) => (
                      <button
                        key={status.value}
                        onClick={() => setPaymentStatus(status.value)}
                        className={`flex-1 p-2 border-2 border-foreground font-bold text-sm transition-colors ${
                          paymentStatus === status.value
                            ? status.color
                            : "bg-white text-foreground hover:bg-foreground/5"
                        }`}
                      >
                        {status.label[lang as keyof typeof status.label] || status.label.en}
                      </button>
                    ))}
                  </div>

                  {/* Notes */}
                  <div className="mb-4">
                    <label className="block text-sm font-bold uppercase tracking-wider text-foreground/60 mb-2">
                      {t.notes}
                    </label>
                    <textarea
                      value={notes}
                      onChange={(e) => setNotes(e.target.value)}
                      placeholder={t.notesPlaceholder}
                      rows={2}
                      className="w-full p-3 border-4 border-foreground bg-white text-foreground font-medium focus:outline-none focus:border-primary-blue resize-none"
                    />
                  </div>

                  {/* Generate Button */}
                  <Button
                    variant="primary"
                    onClick={handleGenerateInvoice}
                    disabled={generating || !selectedPatient || invoiceItems.length === 0}
                    className="w-full text-lg"
                  >
                    {generating ? t.generating : t.generateInvoice}
                  </Button>
                </CardContent>
              </Card>
            )}
          </div>

          {/* Recent Invoices */}
          <div className="lg:col-span-1">
            <Card decorator="blue" decoratorPosition="top-right">
              <CardHeader>
                <h2 className="text-lg font-bold uppercase tracking-wider">{t.recentInvoices}</h2>
              </CardHeader>
              <CardContent>
                {invoices.length === 0 ? (
                  <p className="text-center py-8 text-foreground/60">{t.noInvoicesMessage}</p>
                ) : (
                  <div className="space-y-3">
                    {invoices.map((invoice) => (
                      <div
                        key={invoice.id}
                        className="p-3 border-2 border-foreground bg-white hover:bg-foreground/5 transition-colors"
                      >
                        <div className="flex items-start justify-between">
                          <div className="min-w-0">
                            <p className="font-bold text-sm">{invoice.invoice_number}</p>
                            <p className="text-xs text-foreground/60 truncate">{invoice.patient.full_name}</p>
                            <p className="text-xs text-foreground/40">
                              {new Date(invoice.created_at).toLocaleDateString()}
                            </p>
                          </div>
                          <div className="text-right">
                            <p className="font-black text-primary-blue">{formatCurrency(invoice.total)}</p>
                            <span
                              className={`inline-block px-2 py-0.5 text-xs font-bold uppercase ${
                                PAYMENT_STATUSES.find((s) => s.value === invoice.payment_status)?.color || "bg-foreground/20"
                              }`}
                            >
                              {PAYMENT_STATUSES.find((s) => s.value === invoice.payment_status)?.label[lang as keyof typeof PAYMENT_STATUSES[0]["label"]] || invoice.payment_status}
                            </span>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </main>
  );
}

export default function BillingPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-background flex items-center justify-center"><div className="w-8 h-8 border-4 border-primary-blue border-t-transparent rounded-full animate-spin" /></div>}>
      <BillingPageContent />
    </Suspense>
  );
}
